services:
  - type: web
    name: lapremier-server
    env: node
    buildCommand: npm ci --legacy-peer-deps --no-audit --progress=false
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
